### ルートメッセージのチェック
GET http://localhost:5000/
Content-Type: application/x-www-form-urlencoded;

### Sign in
POST http://localhost:5000/signin HTTP/1.1
Content-Type: application/json

{
  "email": "test1@test",
  "password": "testpassword"
}

### JWTなしの問い合わせ：401エラー
GET http://localhost:5000/users
Content-Type: application/x-www-form-urlencoded;

### JWT付きで問い合わせ：Bearerのあと一つスペースを空けてトークンを書くこと
GET http://localhost:5000/users
Authorization: Bearer

### JWT付きでユーザー登録：Bearerのあと一つスペースを空けてトークンを書くこと
POST http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1NzY3NDA1OH0.MAWXKU6Wi3FwznwDOQnnJE5dQYLE6vAPG-pGlU9O3UE
Content-Type: application/json

{
  "email": "test3@test",
  "password": "testpassword",
  "tasks": [
    { "title": "task1 for test3" },
    { "title": "task2 for test3" },
    { "title": "task3 for test3" }
  ]
}

### JWT付きでユーザー削除：Bearerのあと一つスペースを空けてトークンを書くこと
DELETE http://localhost:5000/users/3
Authorization: Bearer
Content-Type: application/x-www-form-urlencoded
