### ルートメッセージのチェック
GET https://jssamples.herokuapp.com/
Content-Type: application/x-www-form-urlencoded

### Sign in
POST https://jssamples.herokuapp.com/signin
Content-Type: application/json

{"email":"test1@test", "password":"testpassword"}

### JWTなしの問い合わせ：401エラー
GET https://jssamples.herokuapp.com/users
Content-Type: application/x-www-form-urlencoded;

### JWT付きで問い合わせ：Bearerのあと一つスペースを空けてトークンを書くこと
GET https://jssamples.herokuapp.com/users
Authorization: Bearer
